# .github/workflows/ci.yml q
name: CI
on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: echo "TODO: pip install -r requirements.txt"
      - name: Unit tests
        run: echo "TODO: pytest -q"

  metrics-gate:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: "Backtest & metrics gate"
        run: echo "TODO: python -m tools.backtest && python -m tools.check_metrics --rmse-threshold 0.8 --da-threshold 0.8"
