name: CI
on:
  pull_request:
  push:
    branches: [ main ]
  schedule:
    - cron: "30 22 * * 1"  # Mondays 22:30 UTC (~17:30 ET; adjust at DST)
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.12' }
      - run: echo "TODO: pip install -r requirements.txt"
      - run: echo "TODO: pytest -q"
      - run: echo "TODO: python -m tools.backtest && python -m tools.check_metrics --rmse-threshold 0.8 --da-threshold 0.8"
