name: CI
on:
  push:
    branches: [main]     # only runs when you push to main
  workflow_dispatch:      # gives you a "Run workflow" button / CLI trigger

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Unit tests
        run: echo "OK"

  metrics_gate:
    name: metrics-gate    # check shows as: CI / metrics-gate
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: "Backtest & metrics gate"
        run: echo "OK"
