# .github/workflows/ci.yml
name: CI
on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'   # official input
      - name: Install (editable) + dev extras
        run: |
          python -m pip install -U pip
          pip install -e ".[dev]"
      - name: Unit tests
        run: pytest -q

  metrics_gate:
    name: metrics-gate
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Backtest & metrics gate
        run: echo "OK"  # plug real backtest later

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install pre-commit
        run: python -m pip install --upgrade pip pre-commit
      - name: Run pre-commit on all files
        run: pre-commit run --all-files --show-diff-on-failurelint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install pre-commit
        run: python -m pip install --upgrade pip pre-commit
      - name: Run pre-commit on all files
        run: pre-commit run --all-files --show-diff-on-failure
